---
- name: Create NSX-T IP Pool
  hosts: nsxmgr
  gather_facts: no
  tasks:
    - name: Create NSX-T IP Pool
      vmware.ansible_for_nsxt.nsxt_policy_ip_pool:
        nsx_manager_hostname: "{{ nsx_manager_hostname }}"
        nsx_manager_username: "{{ nsx_manager_username }}"
        nsx_manager_password: "{{ nsx_manager_password }}"
        display_name: "{{ item.name }}"
        description: "NSX-T IP Pool"
        prefix_length: 24
        gateway: "{{ item.gateway }}"
        allocation_ranges:
          - start: "{{ item.start_ip }}"
            end: "{{ item.end_ip }}"
        dns_servers: "{{ item.dns_servers }}"
        domain_name: "{{ item.domain_name }}"
        pool_static_subnets:
          - name: "{{ subnet.name }}"
            prefix_length: "{{ subnet.prefix_length }}"
            cidr: "{{ subnet.cidr }}"
            dns_servers: "{{ subnet.dns_servers }}"
            domain_name: "{{ subnet.domain_name }}"
      with_items: "{{ ip_pools }}"
      loop_control:
        loop_var: item
      register: nsx_ip_pool_result

    - name: Display Result
      debug:
        var: vmware.ansible_for_nsxt.nsxt_policy_ip_pool


#---
### Deploys an NSX-T environment
#- hosts: nsxmgr
#  connection: local
#  become: yes
#  gather_facts: False
#  vars_files:
#    - nsx_config.yaml
#  tasks:
#    - name: Create ip pool
#      vmware.ansible_for_nsxt.nsxt_policy_ip_pool:
#        hostname: "{{nsx_hostname}}"
#        username: "{{nsx_username}}"
#        password: "{{nsx_password}}"
#        validate_certs: False
#        display_name: "{{item.pool_display_name}}"
#        pool_static_subnets:
#          - id: test
#            state: "present"
#            subnets: "{{item.subnets}}"
#        state: present
#      with_items:
#        - "{{ip_pools}}"
#
##- name: Create NSX-T IP Pools
##  include_role: create_ip_pool.yml
##  loop: "{{ ip_pools }}"
##  loop_control:
##    loop_var: ippool