---
- name: Create NSX-T IP Pool
  hosts: nsxmgr
  gather_facts: no
  connection: local
  vars_files:
    - nsx_config.yaml
  tasks:
    - name: Create IP Pools
      vmware.ansible_for_nsxt.nsxt_policy_ip_pool:
        hostname: "{{ nsx_hostname }}"
        username: "{{ nsx_username }}"
        password: "{{ nsx_password }}"
        validate_certs: "{{ validate_certs }}"
        display_name: "{{ item.display_name }}"
        pool_static_subnets: "{{ item.pool_static_subnets }}"
        state: "{{ state }}"
      with_items:
        - "{{ ip_pools  }}"
      register: nsx_ip_pool_result

    - name: Display Result
      debug:
        var: ip_pool_result